import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import ReduxProvider from "@/util/ReduxProvider";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],       
  weight: ['300', "400", "500", '600', "700"], 
});



export const metadata: Metadata = {
  title: "FundR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <ReduxProvider>
          <div className="max-w-[1440px] w-full h-full flex flex-col">

            <div className="flex h-full">
            <Sidebar/>
            {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
